
install-dev: install-airbnb-eslint install-prettier

# airbnb를 위한 dependency와 같이 eslint 설치
install-airbnb-eslint:
	yarn add eslint eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-import \
		eslint-config-airbnb

install-prettier:
	yarn add prettier eslint-plugin-prettier eslint-config-prettier
